### ISSUE TITLE
Homework #1

### ISSUE THREAD

**Issue by intrueder** [Potapy4/KottansHomeworks#1]
Please take a look at the readme in the following repository: https://github.com/intrueder/CitizenRegistry/tree/master

**Comment by Nikita505** [comment]
[HomeWork repo](https://github.com/Potapy4/KottansHomeworks/tree/master/Homework%20%231)

Done. Just 2 bugs:
1 - in my locale Humanizer return "вчера", instead "yesterday"
2 - with Indexer_WhenCitizenChanges_RegistryHasNoChanges() - our indexer return null or instance and test can't read the vatID value if instance == null

**Comment by intrueder** [comment]
To fix bug 1, you can remove `Humanizer` package, and install `Humanizer.Core` only.
Or, pass the `en-US` culture as parameter to `.Humanize()` method

And I did not get about bug 2, in that specific test there is no chance to get `null` if indexer has been implemented properly.
